from typing import Protocol, runtime_checkable

KeyMaterial = bytes
@runtime_checkable
class KeyProvider(Protocol):
    """Retrieve/provision/destroy opaque key material; unavailable backends return None."""
    def get_key(self) -> KeyMaterial | None: ...
    def provision_key(self) -> KeyMaterial | None: ...
    def destroy_key(self) -> bool: ...
